PUT http://localhost:3001/api/staffs/6745891fb85edc949d3be30a
Content-Type: application/json

{
    "username" : "Staff 1 updated from VSC"
}
###
PUT http://localhost:3001/api/staffs/6745891fb85edc949d3be30a
Content-Type: application/json

{
    "password" : "Staff_1 updated from VSC"
}

###
PUT http://localhost:3001/api/staffs/67458fa9a5a23577554b019b
Content-Type: application/json

{
    "username" : "Staff 1 updated from VSC",
    "password" : "Staff_1 updated from VSC"
}
