PUT http://localhost:3001/api/admin/6745ea7b212e327b2b1cfd25
Content-Type: application/json

{
    "username" : "Admin 1 updated from VSC"
}
###
PUT http://localhost:3001/api/admin/6745ea9f212e327b2b1cfd28
Content-Type: application/json

{
    "password" : "admin_2 updated from VSC"
}

###
PUT http://localhost:3001/api/admin/6745ea9f212e327b2b1cfd28
Content-Type: application/json

{
    "username" : "Admin 1 updated from VSC",
    "password" : "admin_1 updated from VSC"
}
