POST http://localhost:3001/api/customers/joinQueue
Content-Type: application/json

{
  "queue_id": "6784e52b1fa4416542a9e08f"
}
###
PUT http://localhost:3001/api/customers/677d24d2ae0c8272a1a39f29
Content-Type: application/json

{
  "status": "process"
}