POST http://localhost:3001/api/customers/joinQueue
Content-Type: application/json

{
  "queue_id": "67813c1834fc829b2f71e388"
}
###
PUT http://localhost:3001/api/customers/677d24d2ae0c8272a1a39f29
Content-Type: application/json

{
  "status": "process"
}