# CREATE NEW DESK WITH AUTHORIZATION
POST http://localhost:3001/api/desks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "desk_number": 1
}

###


# CREATE NEW DESK WITHOUT AUTHORIZATION
POST http://localhost:3001/api/desks
Content-Type: application/json

{
    "desk_number": 1
}

###


# READ_ALL_DESKS WITH AUTHORIZATION
GET http://localhost:3001/api/desks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_ALL_DESKS WITHOUT AUTHORIZATION
GET http://localhost:3001/api/desks
###


# READ_SPECIFIC_DESK WITH AUTHORIZATION
GET http://localhost:3001/api/desks/676c19f3863ceaa5ffe75bae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_SPECIFIC_DESK WITHOUT AUTHORIZATION
GET http://localhost:3001/api/desks/676c19f3863ceaa5ffe75bae

###


# UPDATE_SPECIFIC_DESK'S DESK_NUMBER WITH AUTHORIZATION
PUT http://localhost:3001/api/desks/676c19f3863ceaa5ffe75bae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "desk_number" : 100
}
###


# UPDATE_SPECIFIC_DESK'S DESK_NUMBER WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/desks/676c19f3863ceaa5ffe75bae

{
    "desk_number" : 100
}

###


# DELETE_ALL_DESKS WITH AUTHORIZATION
DELETE http://localhost:3001/api/desks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# DELETE_ALL_DESKS WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/desks/

###


# DELETE_SPECIFIC_DESK WITH AUTHORIZATION
DELETE http://localhost:3001/api/desks/676c1c5047119762b9bc6314
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M
###


# DELETE_SPECIFIC_DESK WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/desks/676c1c5047119762b9bc6314