# CREATE NEW USER WITH AUTHORIZATION
POST http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "name" : "VSC 1",
    "email": "userVSC_1@queue.com",
    "password"  : "userVSC_1"
}
###


# CREATE NEW USER WITHOUT AUTHORIZATION
POST http://localhost:3001/api/users

{
    "name" : "VSC 1333",
    "email": "userVSC_1333@queue.com",
    "password"  : "userVSC_1"
}
###


# READ_ALL_USERS WITH AUTHORIZATION
GET http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_ALL_USERS WITHOUT AUTHORIZATION
GET http://localhost:3001/api/users
###


# READ_SPECIFIC_USER WITH AUTHORIZATION
GET http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_SPECIFIC_USER WITHOUT AUTHORIZATION
GET http://localhost:3001/api/users/676c26bd53bdc251e3af28e7

###


# UPDATE_SPECIFIC_USER'S NAME WITH AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "name" : "User 1 updated from VSC"
}
###


# UPDATE_SPECIFIC_USER'S EMAIL WITH AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "email" : "user_1_updated@queue.com"
}

###


# UPDATE_SPECIFIC_USER'S PASSWORD WITH AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "password" : "user_1 password updated from VSC"
}
###


# UPDATE_SPECIFIC_USER'S ALL DATA WITH AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "name" : "Staff 1 updated from VSC",
    "email" : "user_1_updated@queue.com",
    "password" : "123"
}
###


# UPDATE_SPECIFIC_USER'S NAME WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7

{
    "name" : "User 44 updated from VSC"
}
###


# UPDATE_SPECIFIC_USER'S EMAIL WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7

{
    "email" : "user_44_updated@queue.com"
}
###


# UPDATE_SPECIFIC_USER'S PASSWORD WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7

{
    "password" : "user_1 password updated from VSC"
}
###


# UPDATE_SPECIFIC_USER'S ALL DATA WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
Content-Type: application/json

{
    "name" : "Staff 1 updated from VSC",
    "email" : "user_1_updated@queue.com",
    "password" : "user_1 password updated from VSC"
}
###

# DELETE_ALL_USERS WITH AUTHORIZATION
DELETE http://localhost:3001/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M
###


# DELETE_ALL_USERS WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/users/
###


# DELETE_SPECIFIC_USER WITH AUTHORIZATION
DELETE http://localhost:3001/api/users/676c2a5d9b5493139e51898f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M
###


# DELETE_SPECIFIC_USER WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/users/676c26bd53bdc251e3af28e7
