# CREATE NEW QUEUE WITH AUTHORIZATION
POST http://localhost:3001/api/queues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ5ODM5MTcyNGVlZjZlZTViMDI0NzEiLCJpYXQiOjE3MzI4NzEwNzZ9.ETPCoKLoxY1xVEpgcKBjcTQqjEj6PQriJoq7jWkrVhk

{
    "queue_name": "Queue 2",
    "desk_number": 1,
    "max_of_customer": 20
}

###
# CREATE NEW QUEUE WITHOUT AUTHORIZATION
POST http://localhost:3001/api/queues
Content-Type: application/json

{
    "queue_name" : "Queue 1 Created from VSC",
    "desk_number": 2,
    "max_of_customer": 5
}

###
# READ_ALL_QUEUES WITH AUTHORIZATION
GET http://localhost:3001/api/queues
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZDZiZDFjMmZiMjE2ZTNhYWMyNzAiLCJpYXQiOjE3MzI2OTg2NTh9.5KWArVif5mmaCXWj6-dt8cvJ5LfDEnnunka1fx4tWgQ

###
# READ_ALL_QUEUES WITHOUT AUTHORIZATION
GET http://localhost:3001/api/queues
# READ_SPECIFIC_QUEUES WITH AUTHORIZATION
GET http://localhost:3001/api/queues/674700ee50d43efbc92a6167
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3MjI2Mzh9.5ozLwla0sTBR9D2EVhdQnTqqDZTw_ak_73UEgs8tAiY

###
# READ_SPECIFIC_QUEUES WITHOUT AUTHORIZATION
GET http://localhost:3001/api/queues/6746ec074eb5d32febb14c0d

###
# UPDATE_SPECIFIC_QUEUES'S QUEUE_NAME WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/674702c12fc846e540c6fd49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3MjMwMDN9.9bbBpSCkxj0FA79tTV9LrB1DJOJUcRfqrGty1jraklA

{
    "queue_name" : "User 2 updated from VSC"
}
###
# UPDATE_SPECIFIC_QUEUES'S DESK_NUMBER WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/674997520d0d11853f22884d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ5ODM5MTcyNGVlZjZlZTViMDI0NzEiLCJpYXQiOjE3MzI4NzEwNzZ9.ETPCoKLoxY1xVEpgcKBjcTQqjEj6PQriJoq7jWkrVhk

{
    "desk_number" : 2
}

###
# UPDATE_SPECIFIC_USER'S MAX_OF_CUSTOMER WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/674702c12fc846e540c6fd49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3MjMwMDN9.9bbBpSCkxj0FA79tTV9LrB1DJOJUcRfqrGty1jraklA

{
    "max_of_customer" : "23"
}

###
# UPDATE_SPECIFIC_USER'S ALL DATA WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/674997520d0d11853f22884d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3MjMwMDN9.9bbBpSCkxj0FA79tTV9LrB1DJOJUcRfqrGty1jraklA

{
    "queue_name" : "Staff 1 updated from VSC",
    "desk_number" : 2,
    "max_of_customer" : 60
}

###

# UPDATE_SPECIFIC_QUEUES'S QUEUE_NAME WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/6746d81b11c7eace611fdaf7
Content-Type: application/json

{
    "queue_name" : "User 2 updated from VSC"
}
###
# UPDATE_SPECIFIC_QUEUES'S DESK_NUMBER WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/674997520d0d11853f22884d
Content-Type: application/json

{
    "desk_number" : 2
}

###
# UPDATE_SPECIFIC_QUEUES'S MAX_OF_CUSTOMER WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/67458fa9a5a23577554b019b
Content-Type: application/json

{
    "max_of_customer" : "user_1 password updated from VSC"
}

###
# UPDATE_SPECIFIC_QUEUES'S ALL DATA WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/67458fa9a5a23577554b019b
Content-Type: application/json
{
    "queue_name" : "Staff 1 updated from VSC",
    "desk_number" : "user_1_updated@queue.com",
    "max_of_customer" : "user_1 password updated from VSC"
}

###
# DELETE_ALL_QUEUES WITH AUTHORIZATION
DELETE http://localhost:3001/api/queues/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3NzgyNzJ9.IDGs1DXs6rjZfUDeaPuYStDQM6mYpngisRHax_6oZfk

###
# DELETE_ALL_USERS WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/queues/

###
# DELETE_SPECIFIC_USER WITH AUTHORIZATION
DELETE http://localhost:3001/api/queues/674702c12fc846e540c6fd49
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzQ2ZmVlOTBhN2RmOTI4OGJkNjQ5YjUiLCJpYXQiOjE3MzI3MjMwMDN9.9bbBpSCkxj0FA79tTV9LrB1DJOJUcRfqrGty1jraklA
###
# DELETE_SPECIFIC_USER WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/queues/67459185ba6dbc7391054617

