# CREATE NEW QUEUE WITH AUTHORIZATION
POST http://localhost:3001/api/queues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "queue_name": "VSC 2",
    "desk_number": 1,
    "max_of_customer": 20
}
###


# CREATE NEW QUEUE WITH STATUS and AUTHORIZATION
POST http://localhost:3001/api/queues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "queue_name": "VSC Queue 1",
    "desk_number": 1,
    "max_of_customer": 20,
    "status" : "Active"
}

###


# CREATE NEW QUEUE WITHOUT AUTHORIZATION
POST http://localhost:3001/api/queues
Content-Type: application/json

{
    "queue_name" : "Queue 1 Created from VSC",
    "desk_number": 2,
    "max_of_customer": 20
}

###


# READ_ALL_QUEUES WITH AUTHORIZATION
GET http://localhost:3001/api/queues
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_ALL_QUEUES WITHOUT AUTHORIZATION
GET http://localhost:3001/api/queues

###


# READ_SPECIFIC_QUEUES WITH AUTHORIZATION
GET http://localhost:3001/api/queues/676c2034860ee972d7991cae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# READ_SPECIFIC_QUEUES WITHOUT AUTHORIZATION
GET http://localhost:3001/api/queues/676c2034860ee972d7991cae

###


# UPDATE_SPECIFIC_QUEUES'S QUEUE_NAME WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "queue_name" : "VSC queue 2 updated from VSC"
}
###


# UPDATE_SPECIFIC_QUEUES'S DESK_NUMBER WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "desk_number" : 3
}

###


# UPDATE_SPECIFIC_QUEUES'S MAX_OF_CUSTOMER WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "max_of_customer" : "23"
}

###


# UPDATE_SPECIFIC_QUEUES'S STATUS WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "status" : "Nonactive"
}

###


# UPDATE_SPECIFIC_QUEUES'S ALL DATA WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

{
    "queue_name" : "VSC 1 updated from VSC TWICE",
    "desk_number" : 1,
    "max_of_customer" : 10,
    "status" : "Active"
}
###


# UPDATE_SPECIFIC_QUEUES'S QUEUE_NAME WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json

{
    "queue_name" : "User 2 updated from VSC"
}
###


# UPDATE_SPECIFIC_QUEUES'S DESK_NUMBER WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/674997520d0d11853f22884d
Content-Type: application/json

{
    "desk_number" : 2
}
###


# UPDATE_SPECIFIC_QUEUES'S MAX_OF_CUSTOMER WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae
Content-Type: application/json

{
    "max_of_customer" : "user_1 password updated from VSC"
}

###


# UPDATE_SPECIFIC_QUEUES'S STATUS WITHOUT AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae

{
    "status" : "Nonactive"
}

###


# UPDATE_SPECIFIC_QUEUES'S ALL DATA WITH AUTHORIZATION
PUT http://localhost:3001/api/queues/676c2034860ee972d7991cae

{
    "queue_name" : "Staff 1 updated from VSC",
    "desk_number" : "user_1_updated@queue.com",
    "max_of_customer" : "user_1 password updated from VSC",
    "status" : "Active"
}
###


# DELETE_ALL_QUEUES WITH AUTHORIZATION
DELETE http://localhost:3001/api/queues/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M

###


# DELETE_ALL_QUEUES'S WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/queues/
###


# DELETE_SPECIFIC_QUEUES'S WITH AUTHORIZATION
DELETE http://localhost:3001/api/queues/676c2416de9755600813253e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2NzU3NDIzNmM4M2NkYzBhZTI0NjQ0NzYiLCJpYXQiOjE3MzUxMzc0MDd9.e7uDV_TANf7ii5cq_INSvYKv-p_L0oegwgPInKRo98M
###


# DELETE_SPECIFIC_QUEUES'S WITHOUT AUTHORIZATION
DELETE http://localhost:3001/api/queues/676c2034860ee972d7991cae

